#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : crudini
Version  : 0.5
Release  : 15
URL      : https://pypi.python.org/packages/source/c/crudini/crudini-0.5.tgz
Source0  : https://pypi.python.org/packages/source/c/crudini/crudini-0.5.tgz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0
Requires: crudini-bin
Requires: crudini-python
BuildRequires : iniparse
BuildRequires : pbr
BuildRequires : pip
BuildRequires : python-dev
BuildRequires : setuptools

%description
crudini - A utility for manipulating ini files
Usage: crudini --set [OPTION]...   config_file section   [param] [value]
or:  crudini --get [OPTION]...   config_file [section] [param]
or:  crudini --del [OPTION]...   config_file section   [param] [list value]
or:  crudini --merge [OPTION]... config_file [section]

%package bin
Summary: bin components for the crudini package.
Group: Binaries

%description bin
bin components for the crudini package.


%package python
Summary: python components for the crudini package.
Group: Default

%description python
python components for the crudini package.


%prep
%setup -q -n crudini-0.5

%build
python2 setup.py build -b py2

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
pushd tests && ./test.sh && popd
%install
rm -rf %{buildroot}
python2 setup.py build -b py2 install --root=%{buildroot}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/crudini

%files python
%defattr(-,root,root,-)
/usr/lib/python*/*
